name: django-dev
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2022.10.11
  - libcxx=14.0.6
  - libffi=3.3
  - ncurses=6.3
  - openssl=1.1.1s
  - python=3.10.0
  - readline=8.2
  - sqlite=3.40.0
  - tk=8.6.12
  - tzdata=2022g
  - wheel=0.37.1
  - xz=5.2.8
  - zlib=1.2.13
  - pip==22.3.1
  - pip:
    - certifi==2022.9.24
    - setuptools==65.5.0
    - -r ../requirements/requirements.dev.txt