# Generated by Django 4.1 on 2022-12-14 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=30)),
                ('client_email', models.CharField(blank=True, max_length=100, null=True)),
                ('client_phone', models.CharField(max_length=30)),
                ('client_addr', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.IntegerField()),
                ('product_name', models.CharField(max_length=50)),
                ('product_price', models.FloatField(default=0)),
                ('product_img', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_total_base', models.FloatField(default=0)),
                ('order_total_discount', models.FloatField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_front.client')),
                ('order_discount', models.ManyToManyField(to='apps_front.discount')),
                ('payment_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_front.payment')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_quantity', models.IntegerField(default=0)),
                ('product_desc', models.CharField(blank=True, max_length=300, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_front.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_front.product')),
            ],
        ),
    ]
