# Generated by Django 4.1 on 2022-12-14 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_front', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cart',
            table='cart',
        ),
        migrations.AlterModelTable(
            name='client',
            table='client',
        ),
        migrations.AlterModelTable(
            name='discount',
            table='discount',
        ),
        migrations.AlterModelTable(
            name='order',
            table='order',
        ),
        migrations.AlterModelTable(
            name='payment',
            table='payment',
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
    ]
