# Generated by Django 4.1 on 2022-12-15 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_front', '0003_delivery_rename_order_discount_order_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 15, 15, 30, 30, 236908)),
        ),
    ]
