# Generated by Django 4.1 on 2022-12-19 09:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("apps_front", "0009_inventory_variant_alter_order_create_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventory",
            name="variant",
        ),
        migrations.AlterField(
            model_name="order",
            name="create_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 19, 9, 44, 9, 431289)
            ),
        ),
        migrations.AddField(
            model_name="inventory",
            name="variant",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="apps_front.variant",
            ),
            preserve_default=False,
        ),
    ]
