# Generated by Django 4.1 on 2022-12-19 09:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "apps_front",
            "0010_remove_inventory_variant_alter_order_create_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="create_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 19, 9, 45, 39, 407534)
            ),
        ),
        migrations.AlterUniqueTogether(
            name="inventory",
            unique_together={("product", "variant")},
        ),
    ]
