# Generated by Django 4.1 on 2022-12-22 13:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("apps_front", "0011_alter_order_create_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="create_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 22, 13, 52, 59, 205551)
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="apps_front.delivery",
            ),
        ),
    ]
