# Generated by Django 4.1 on 2022-12-22 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps_front", "0012_alter_order_create_date_alter_order_delivery"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="create_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 22, 13, 54, 25, 672536)
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="discount",
            field=models.ManyToManyField(
                blank=True, null=True, to="apps_front.discount"
            ),
        ),
    ]
